/*
 * EEPROM_MemoryMap.h
 *
 *  Created on: Jan 14, 2018
 *      Author: Kaan
 */

#ifndef EEPROM_MEMORYMAP_H_
#define EEPROM_MEMORYMAP_H_

#include "RadioManager.h"
#include "DataChannelManager.h"
//#include "CalibrationManager.h"
//#include "ChannelManager.h"


#define E2PROM_DEVICE_START_INDEX									16

#define E2PROM_DEVICE_UNIQUE_ID_INDEX  								E2PROM_DEVICE_START_INDEX
#define E2PROM_DEVICE_UNIQUE_ID_LENGTH 								2

#define E2PROM_DEVICE_BSP_CODE_INDEX								(E2PROM_DEVICE_UNIQUE_ID_INDEX + E2PROM_DEVICE_UNIQUE_ID_LENGTH)
#define E2PROM_DEVICE_BSP_CODE_LENGTH 								2

#define E2PROM_DEVICE_FIRMWARE_VERSION_INDEX						(E2PROM_DEVICE_BSP_CODE_INDEX + E2PROM_DEVICE_BSP_CODE_LENGTH)
#define E2PROM_DEVICE_FIRMWARE_VERSION_LENGTH						8


/*LoRa Definitions */
#define E2PROM_LORA_UNIQUE_ID_INDEX 								(E2PROM_DEVICE_FIRMWARE_VERSION_INDEX + E2PROM_DEVICE_FIRMWARE_VERSION_LENGTH)
#define E2PROM_LORA_UNIQUE_ID_LENGTH								(sizeof(unitNo_t))

#define E2PROM_LORA_GATEWAY_ID_INDEX								(E2PROM_LORA_UNIQUE_ID_INDEX + E2PROM_LORA_GATEWAY_ID_LENGTH)
#define E2PROM_LORA_GATEWAY_ID_LENGTH								1

#define E2PROM_LORA_TX_POWER_INDEX									(E2PROM_LORA_GATEWAY_ID_INDEX + E2PROM_LORA_GATEWAY_ID_LENGTH)
#define E2PROM_LORA_TX_POWER_LENGTH									1

#define E2PROM_LORA_CODING_RATE_INDEX								(E2PROM_LORA_TX_POWER_INDEX + E2PROM_LORA_TX_POWER_LENGTH)
#define E2PROM_LORA_CODING_RATE_LENGTH								1

#define E2PROM_LORA_BANDWIDTH_INDEX									(E2PROM_LORA_CODING_RATE_INDEX + E2PROM_LORA_CODING_RATE_LENGTH)
#define E2PROM_LORA_BANDWIDTH_LENGTH								1

#define E2PROM_LORA_ROUTING_MAP_INDEX								(E2PROM_LORA_BANDWIDTH_INDEX + E2PROM_LORA_BANDWIDTH_LENGTH)
#define E2PROM_LORA_ROUTING_MAP_LENGTH 								sizeof(sRoutingTableElement) * MAX_STATIC_ROUTING_TABLE_SIZE

/* Data Channels */

#define E2PROM_DATA_CHANNELS_INDEX									( E2PROM_LORA_ROUTING_MAP_INDEX + E2PROM_LORA_ROUTING_MAP_LENGTH )
#define E2PROM_DATA_CHANNELS_LENGTH									sizeof( ChannelInfoStr ) * CHANNEL_MANAGER_CHANNEL_COUNT




/* Run Configurations */


/*Sensor Calibrations */



#endif /* EEPROM_MEMORYMAP_H_ */
